[package]
name = "isla-frontend-matrix"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "isla-frontend-matrix"
test = false

[dependencies]
matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk.git" }
anyhow = "1"
dirs = "5.0.1"
rand = "0.8.5"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.15"
serde = "1.0.164"
serde_json = "1.0.97"
isla-proto = { path = "../isla-proto" }
tonic = "0.9.2"
